name: Daily Tech Blog Draft

on:
  schedule:
    - cron: "0 3 * * *" # daily 8:30 AM IST
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install node-fetch

      - run: node generate.js
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - run: |
          git config user.name "ai-blog-bot"
          git config user.email "ai@bot.com"
          git add .
          git commit -m "chore: add daily tech draft"
          git push
